### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by suprokash-1**
For a noob like me, your content comes as a boon.

Your no-nonsense, to-the-point & sequential content is gold!

More power to you & God bless...

### CODE REVIEW

**Comment by suprokash-1** [comment]
Hi, I am really sorry to send this pull request...Since i am a clueless noob, i didn't deserve a response from you... Time is money, right!

Please forgive me for this unwanted-intrusion...

**Comment by ggelashvili** [comment]
Hey, no worries. I'm sorry, I just saw your PR, for some reason I did not get the email about the initial PR, just saw the email when you added this comment. I sometimes forget to add the links and end up adding multiple links at the same time. I would've accepted your PR for sure if I saw it. I'll make sure to check any open PRs before pushing updates.

Thank you very much & thank you for trying to help, I really appreciate it.

**Comment by ggelashvili** [comment]
Just want to make it clear that I did not mean to ignore your PR at all, I honestly did not see the initial email, so I apologize again. Thank you for the kind words & I would never ignore you or anyone as you can see from my replies on YouTube comments. I try to reply to everyone as long as I am notified about it but sometimes I don't get notified.

**Comment by suprokash-1** [comment]
I get you... Please, Bury the hatchet!

**Pull request closed without merging**
